# Generated by Django 5.1.1 on 2024-09-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
    ]
