# Generated by Django 5.1.1 on 2024-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0002_remove_invoice_amount_remove_invoice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='course',
            field=models.CharField(default='Unknown Course', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='student_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
