# Generated by Django 5.1.1 on 2024-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0004_invoiceitem_parent_contact_invoiceitem_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='installment1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment2_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
